name: build
on:
   pull_request:
   workflow_dispatch:


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Build Zola + upload Pages artifact
        uses: getzola/github-pages@435a833fd3f1edcb28d70576c89e30a6365cd8f7
        with:
          zola_version: v0.22.0
